### ISSUE TITLE
handle (failed)net::ERR_CONNECTION_TIMED_OUT 

### ISSUE THREAD

**Issue by gumitrathore** [simoneb/axios-hooks#976]
not able to catch error and breaking at
`Uncaught TypeError: Cannot read properties of undefined (reading 'data')
    at reducer (index.js:167:1)
    at updateReducer (react-dom.development.js:15318:1)
    at Object.useReducer (react-dom.development.js:16425:1)
    at Object.useReducer (react.development.js:1512:1)
    at useAxios (index.js:274:1)`

**Comment by simoneb** [comment]
can you please provide a running repro? e.g. using codesandbox
